version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sst_backend
    ports:
      - "8002:8000"  # Espone il backend FastAPI sulla porta 8002
    environment:
      - ENV=production
    restart: always

  frontend:
    build: ./frontend
    container_name: sst_frontend
    ports:
      - "3000:3000"  # Espone il frontend React sulla porta 3000
    depends_on:
      - backend
    restart: always
